### ISSUE TITLE
Cannot install on R version 3.5.0

### ISSUE THREAD

**Issue by blukasz14** [USGS-R/DVstats#6]
Anyone else experience this issue?
![dvstats](https://user-images.githubusercontent.com/40276185/41431286-05ac78a8-6fd8-11e8-9d91-3e4ba0ed799e.JPG)

**Comment by ldecicco-USGS** [comment]
If you follow the directions in "Package Installation" on the readme, you'll see a way to install `DVstats` without using the devtools `install_github` function. You'll need to add "GRAN" to your list of possible R repositories, and then DVstats (as well as all the "smwr" dependencies) will install using install.packages.

But...if you really want to install from the `install_github` function, you'll need to install the appropriate "Rtools" for R 3.5, and manually install the smwr packages (since they aren't on CRAN either).

If the instructions aren't clear here:
https://github.com/USGS-R/DVstats
let me know

**Comment by blukasz14** [comment]
Thanks you, pasting that code in the console worked.

**Comment by blukasz14** [comment]
Thank you, pasting that code in the console worked.
